# global robot configuration and details

robot_config:

    joint_names:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    arm_id: panda
        # Activate rate limiter? [true|false]
    joint_limit_warning_threshold: 0.1 # [rad]
    rate_limiting: true
    # Cutoff frequency of the low-pass filter. Set to >= 1000 to deactivate.
    cutoff_frequency: 100
    # Internal controller for motion generators [joint_impedance|cartesian_impedance]
    internal_controller: joint_impedance

    neutral_pose:
        panda_joint1: -0.017792060227770554 
        panda_joint2: -0.7601235411041661  
        panda_joint3: 0.019782607023391807 
        panda_joint4: -2.342050140544315 
        panda_joint5: 0.029840531355804868 
        panda_joint6: 1.5411935298621688 
        panda_joint7: 0.7534486589746342 

    collecting_pose:
        panda_joint1: -0.012692199049811606 
        panda_joint2: 0.15991111190765225  
        panda_joint3: -0.013538261069621848
        panda_joint4: -2.154583692902807 
        panda_joint5: 0.029400776573353344
        panda_joint6: 2.2792713105123803 
        panda_joint7: 0.753693321040935

    pose_undeformed:
        panda_joint1: -0.010422303364595799
        panda_joint2: 0.26857981667646746
        panda_joint3: -0.006368918233469389
        panda_joint4: -2.1733175249601664
        panda_joint5: -0.0034871803985793326
        panda_joint6: 2.433989388121499
        panda_joint7: 0.7683675387418931

    pose1:
        panda_joint1: -0.01021096985721838
        panda_joint2: 0.2768584573101585
        panda_joint3: -0.004917372449524618
        panda_joint4: -2.1732639993896763
        panda_joint5: -0.003489720141732147
        panda_joint6: 2.4377258550870597
        panda_joint7: 0.768375503277656

    pose2:
        panda_joint1: -0.01020790333402046
        panda_joint2: 0.2800524360251774
        panda_joint3: -0.004965964485154001
        panda_joint4: -2.172054052888778
        panda_joint5: -0.00369166454155412
        panda_joint6: 2.438934453618295
        panda_joint7: 0.767877448733567

    pose_undeformed2:
        panda_joint1: 0.01777338214244759
        panda_joint2: 0.2758376222158733
        panda_joint3: -0.0744730108537172
        panda_joint4: -2.149218857803999
        panda_joint5: -0.003666772347150577
        panda_joint6: 2.390657784117592
        panda_joint7: 0.7153880630847231

    pose3:
        panda_joint1: 0.017676215794264222
        panda_joint2: 0.2943181867855102
        panda_joint3: -0.07242269966767312
        panda_joint4: -2.1534060189978734
        panda_joint5: -0.003468590844723239
        panda_joint6: 2.40623620349832
        panda_joint7: 0.7167686473247078

    pose4:
        panda_joint1: 0.017568111975975256
        panda_joint2: 0.2991553466612832
        panda_joint3: -0.07292188268441585
        panda_joint4: -2.1523708896065545
        panda_joint5: -0.003538315692387975
        panda_joint6: 2.406312129749192
        panda_joint7: 0.7167616409973965

    reset_pose:
        panda_joint1: -0.022741129955352355
        panda_joint2: -0.35965990199494513  
        panda_joint3: -0.039269722086130866 
        panda_joint4: -0.6519538549998808 
        panda_joint5: 0.02654991794843978
        panda_joint6: 0.4789563876298161 
        panda_joint7: 0.7538603618658251    

    joint_config:
        joint_acceleration_limit:
            panda_joint1: 15.0 # rad / sec^2
            panda_joint2: 7.5  # rad / sec^2
            panda_joint3: 10.0 # rad / sec^2
            panda_joint4: 12.5 # rad / sec^2
            panda_joint5: 15.0 # rad / sec^2
            panda_joint6: 20.0 # rad / sec^2
            panda_joint7: 20.0 # rad / sec^2
            # panda_finger_joint1: 12.0 # rad / sec^2
            # panda_finger_joint2: 12.0 # rad / sec^2

        joint_velocity_limit:
            panda_joint1: 2.1750 # rad / sec
            panda_joint2: 2.1750 # rad / sec
            panda_joint3: 2.1750 # rad / sec
            panda_joint4: 2.1750 # rad / sec
            panda_joint5: 2.6100 # rad / sec
            panda_joint6: 2.6100 # rad / sec
            panda_joint7: 2.6100 # rad / sec
            # panda_finger_joint1: 2.0 # rad / sec
            # panda_finger_joint2: 2.0 # rad / sec

        joint_position_limit:
            lower: 
                panda_joint1: -2.8973 # rad
                panda_joint2: -1.7628 # rad
                panda_joint3: -2.8973 # rad
                panda_joint4: -3.0718 # rad
                panda_joint5: -2.8973 # rad
                panda_joint6: -0.0175 # rad
                panda_joint7: -2.8973 # rad
            upper:
                panda_joint1: 2.8973 # rad
                panda_joint2: 1.7628 # rad
                panda_joint3: 2.8973 # rad
                panda_joint4: -0.0698 # rad
                panda_joint5: 2.8973 # rad
                panda_joint6: 3.7525 # rad
                panda_joint7: 2.8973 # rad

        joint_effort_limit:
            panda_joint1: 87 # Nm
            panda_joint2: 87 # Nm
            panda_joint3: 87 # Nm
            panda_joint4: 87 # Nm
            panda_joint5: 12 # Nm
            panda_joint6: 12 # Nm
            panda_joint7: 12 # Nm      

    realtime_config: enforce
    # Configure the initial defaults for the collision behavior reflexes.
    collision_config:
      lower_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
      upper_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
      lower_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
      upper_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
      lower_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
      upper_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
      lower_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
      upper_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]      

gripper_config:
  joint_names:
    - panda_finger_joint1
    - panda_finger_joint2
  default_speed: 0.1  # [m/s]
  default_grasp_epsilon:
    inner: 0.005 # [m]
    outer: 0.005 # [m]

controllers_config:
    position_controller: "franka_ros_interface/position_joint_position_controller"
    torque_controller: "franka_ros_interface/effort_joint_torque_controller"
    impedance_controller: "franka_ros_interface/effort_joint_impedance_controller"
    velocity_controller: "franka_ros_interface/velocity_joint_velocity_controller"
    trajectory_controller: "position_joint_trajectory_controller"
    default_controller: "position_joint_trajectory_controller" # for safety, always set a position controller as default
    joint_impedance_controller: "franka_ros_interface/joint_impedance_controller"    
    cartesian_impedance_controller: "franka_ros_controllers/CartesianImpedanceController"
    command_timeout: 0.2 # timeout to wait for consecutive torque control commands (or velocity) when using torque (or velocity) control. If timeout is violated, the controller interface will automatically switch to default controller for safety

    # cartesian_impedance_controller: "franka_ros_interface/cartesian_impedance_controller"
